#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-latest_ruby
Version  : 0.0.4
Release  : 4
URL      : https://rubygems.org/downloads/latest_ruby-0.0.4.gem
Source0  : https://rubygems.org/downloads/latest_ruby-0.0.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Zlib
BuildRequires : ruby
BuildRequires : rubygem-bacon
BuildRequires : rubygem-blockenspiel
BuildRequires : rubygem-coderay
BuildRequires : rubygem-method_source
BuildRequires : rubygem-pry
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-slop
BuildRequires : rubygem-versionomy

%description
Latest Ruby
===========
* Repository: [https://github.com/kyrylo/latest_ruby][repo]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n latest_ruby-0.0.4
gem spec %{SOURCE0} -l --ruby > rubygem-latest_ruby.gemspec

%build
gem build rubygem-latest_ruby.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
latest_ruby-0.0.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/latest_ruby-0.0.4
rspec -Ilib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/latest_ruby-0.0.4.gem
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/JRuby/cdesc-JRuby.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/JRuby/link-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/JRuby/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/JRuby/source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/JRuby/version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/JRuby/web_source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/JRubyRetriever/cdesc-JRubyRetriever.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/JRubyRetriever/retrieve-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MRI/cdesc-MRI.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MRI/link-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MRI/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MRI/short_ver-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MRI/source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MRI/version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MRIRetriever/cdesc-MRIRetriever.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MRIRetriever/retrieve-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MacRuby/cdesc-MacRuby.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MacRuby/link-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MacRuby/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MacRuby/source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MacRuby/version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MacRubyRetriever/cdesc-MacRubyRetriever.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MacRubyRetriever/retrieve-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MagLev/cdesc-MagLev.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MagLev/link-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MagLev/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MagLev/source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MagLev/version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MagLevRetriever/cdesc-MagLevRetriever.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/MagLevRetriever/retrieve-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/Rubinius/cdesc-Rubinius.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/Rubinius/link-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/Rubinius/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/Rubinius/source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/Rubinius/version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/RubiniusRetriever/cdesc-RubiniusRetriever.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/RubiniusRetriever/retrieve-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/Ruby/cdesc-Ruby.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/Ruby/filename-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/Ruby/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/RubyVersion/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/RubyVersion/cdesc-RubyVersion.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/RubyVersion/get_version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/RubyVersion/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/cdesc-Latest.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/jruby-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/macruby-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/maglev-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/rbx-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/rubinius-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/ruby-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/ruby18-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/ruby19-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/ruby20-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/ruby21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/Latest/ruby22-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/latest_ruby-0.0.4/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/LICENCE
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/README.md
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/VERSION
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/latest_ruby.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/lib/latest_ruby.rb
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/lib/latest_ruby/retrievers/jruby_retriever.rb
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/lib/latest_ruby/retrievers/macruby_retriever.rb
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/lib/latest_ruby/retrievers/maglev_retriever.rb
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/lib/latest_ruby/retrievers/mri_retriever.rb
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/lib/latest_ruby/retrievers/rubinius_retriever.rb
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/lib/latest_ruby/rubies/jruby.rb
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/lib/latest_ruby/rubies/macruby.rb
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/lib/latest_ruby/rubies/maglev.rb
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/lib/latest_ruby/rubies/mri.rb
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/lib/latest_ruby/rubies/rubinius.rb
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/lib/latest_ruby/ruby.rb
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/lib/latest_ruby/ruby_version.rb
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/spec/helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/latest_ruby-0.0.4/spec/latest_ruby_spec.rb
/usr/lib64/ruby/gems/2.2.0/specifications/latest_ruby-0.0.4.gemspec
