#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-latest_ruby
Version  : 0.0.5
Release  : 9
URL      : https://rubygems.org/downloads/latest_ruby-0.0.5.gem
Source0  : https://rubygems.org/downloads/latest_ruby-0.0.5.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Zlib
BuildRequires : ruby
BuildRequires : rubygem-bacon
BuildRequires : rubygem-blockenspiel
BuildRequires : rubygem-coderay
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-method_source
BuildRequires : rubygem-pry
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-slop
BuildRequires : rubygem-versionomy

%description
Latest Ruby
===========
* Repository: [https://github.com/kyrylo/latest_ruby][repo]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n latest_ruby-0.0.5
gem spec %{SOURCE0} -l --ruby > rubygem-latest_ruby.gemspec

%build
export LANG=C
gem build rubygem-latest_ruby.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
latest_ruby-0.0.5.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/latest_ruby-0.0.5
rspec -I.:lib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/latest_ruby-0.0.5.gem
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/LICENCE
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/README.md
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/latest_ruby.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/lib/latest_ruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/lib/latest_ruby/retrievers/jruby_retriever.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/lib/latest_ruby/retrievers/macruby_retriever.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/lib/latest_ruby/retrievers/maglev_retriever.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/lib/latest_ruby/retrievers/mri_retriever.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/lib/latest_ruby/retrievers/rubinius_retriever.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/lib/latest_ruby/rubies/jruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/lib/latest_ruby/rubies/macruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/lib/latest_ruby/rubies/maglev.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/lib/latest_ruby/rubies/mri.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/lib/latest_ruby/rubies/rubinius.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/lib/latest_ruby/ruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/lib/latest_ruby/ruby_version.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/spec/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.5/spec/latest_ruby_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/latest_ruby-0.0.5.gemspec
