#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-latest_ruby
Version  : 0.0.4
Release  : 8
URL      : https://rubygems.org/downloads/latest_ruby-0.0.4.gem
Source0  : https://rubygems.org/downloads/latest_ruby-0.0.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Zlib
BuildRequires : ruby
BuildRequires : rubygem-bacon
BuildRequires : rubygem-pry
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-versionomy

%description
Latest Ruby
===========
* Repository: [https://github.com/kyrylo/latest_ruby][repo]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n latest_ruby-0.0.4
gem spec %{SOURCE0} -l --ruby > rubygem-latest_ruby.gemspec

%build
gem build rubygem-latest_ruby.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
latest_ruby-0.0.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/latest_ruby-0.0.4.gem
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/LICENCE
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/README.md
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/latest_ruby.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/lib/latest_ruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/lib/latest_ruby/retrievers/jruby_retriever.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/lib/latest_ruby/retrievers/macruby_retriever.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/lib/latest_ruby/retrievers/maglev_retriever.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/lib/latest_ruby/retrievers/mri_retriever.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/lib/latest_ruby/retrievers/rubinius_retriever.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/lib/latest_ruby/rubies/jruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/lib/latest_ruby/rubies/macruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/lib/latest_ruby/rubies/maglev.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/lib/latest_ruby/rubies/mri.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/lib/latest_ruby/rubies/rubinius.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/lib/latest_ruby/ruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/lib/latest_ruby/ruby_version.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/spec/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/latest_ruby-0.0.4/spec/latest_ruby_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/latest_ruby-0.0.4.gemspec
